# Generated by Django 5.2.6 on 2025-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('cliente_id', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('vigente', 'vigente'), ('vencido', 'vencido'), ('rescindido', 'rescindido')], default='vigente', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Contrato',
                'managed': False,
            },
        ),
    ]
