# Generated by Django 5.2.6 on 2025-09-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('vigente', 'vigente'), ('vencido', 'vencido'), ('rescindido', 'rescindido')], default='vigente', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('servicio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Servicio')),
                ('tipo', models.CharField(choices=[('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Mensual', 'Mensual')], default='Anual', max_length=50, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total')),
                ('pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Pagado')),
                ('porcentajePagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Porcentaje Pagado')),
                ('estudiantes', models.PositiveIntegerField(default=0, verbose_name='Número de Estudiantes')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('clausulas', models.JSONField(blank=True, default=list, verbose_name='Cláusulas')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'contrato',
                'managed': True,
            },
        ),
    ]
