# Generated by Django 5.2.6 on 2025-09-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contrato_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contrato',
            table='contrato',
        ),
    ]
