# Generated by Django 5.2.6 on 2025-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('financial', 'KPI Financiero'), ('operational', 'KPI Operacional'), ('client', 'KPI de Cliente'), ('inventory', 'KPI de Inventario'), ('production', 'KPI de Producción')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('calculation_formula', models.TextField()),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kpi_definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetricAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('metric_id', models.IntegerField()),
                ('kpi_definition_id', models.IntegerField(blank=True, null=True)),
                ('alert_level', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Crítico')], max_length=20)),
                ('message', models.TextField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metric_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('metric_type', models.CharField(choices=[('financial', 'Métrica Financiera'), ('operational', 'Métrica Operacional'), ('client', 'Métrica de Cliente'), ('inventory', 'Métrica de Inventario'), ('production', 'Métrica de Producción')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'metrics',
                'ordering': ['-calculated_at'],
                'unique_together': {('tenant_id', 'name', 'period_start', 'period_end')},
            },
        ),
    ]
