# Generated by Django 5.2.6 on 2025-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_id', models.IntegerField()),
                ('item_type', models.CharField(choices=[('varilla', 'varilla'), ('cuadro', 'cuadro'), ('producto_terminado', 'producto_terminado'), ('material_impresion', 'material_impresion'), ('material_recordatorio', 'material_recordatorio'), ('material_diseno', 'material_diseno')], max_length=25)),
                ('item_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'DetallePedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('cliente_id', models.IntegerField()),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('en_proceso', 'en_proceso'), ('entregado', 'entregado'), ('cancelado', 'cancelado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Pedido',
                'managed': False,
            },
        ),
    ]
