# Generated by Django 5.2.6 on 2025-09-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Pedido')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente/Colegio')),
                ('servicio', models.CharField(choices=[('Impresión Digital', 'Impresión Digital'), ('Fotografía Escolar', 'Fotografía Escolar'), ('Promoción Escolar', 'Promoción Escolar'), ('Enmarcado', 'Enmarcado'), ('Retoque Fotográfico', 'Retoque Fotográfico'), ('Recordatorios', 'Recordatorios'), ('Ampliaciones', 'Ampliaciones'), ('Fotografía de Eventos', 'Fotografía de Eventos'), ('Sesión Familiar', 'Sesión Familiar')], default='Impresión Digital', max_length=50, verbose_name='Tipo de Servicio')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Listo para Entrega', 'Listo para Entrega'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('fechaPedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Total')),
                ('adelanto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Adelanto Pagado')),
                ('especificaciones', models.TextField(blank=True, null=True, verbose_name='Especificaciones Técnicas')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['-fechaPedido'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Proyecto')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('tipo', models.CharField(choices=[('Fotografía Escolar', 'Fotografía Escolar'), ('Promoción Escolar', 'Promoción Escolar'), ('Evento Social', 'Evento Social'), ('Sesión Familiar', 'Sesión Familiar'), ('Fotografía Comercial', 'Fotografía Comercial'), ('Enmarcado', 'Enmarcado'), ('Impresión Digital', 'Impresión Digital'), ('Retoque Fotográfico', 'Retoque Fotográfico')], default='Fotografía Escolar', max_length=50, verbose_name='Tipo de Proyecto')),
                ('estado', models.CharField(choices=[('Planificación', 'Planificación'), ('En Progreso', 'En Progreso'), ('Revision', 'Revisión'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Planificación', max_length=20, verbose_name='Estado')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Presupuesto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
