# Generated by Django 5.2.6 on 2025-09-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalles',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles Adicionales'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='diseño',
            field=models.TextField(blank=True, null=True, verbose_name='Diseño'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fotografias',
            field=models.JSONField(blank=True, default=list, verbose_name='Fotografías'),
        ),
    ]
