# Generated by Django 5.2.6 on 2025-09-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pedido_detalles_pedido_diseño_pedido_fotografias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': True, 'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='adelanto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='especificaciones',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fechaEntrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fechaPedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='detalles',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalles Adicionales'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='diseño',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Diseño'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Producción', 'Producción'), ('Entregado', 'Entregado')], default='Nuevo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fotografias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fotografías Asociadas'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='servicio',
            field=models.CharField(choices=[('Impresión Minilab', 'Impresión Minilab'), ('Enmarcado', 'Enmarcado'), ('Recordatorio Escolar', 'Recordatorio Escolar'), ('Retoque Fotográfico', 'Retoque Fotográfico')], default='Impresión Minilab', max_length=50, verbose_name='Tipo de Servicio'),
        ),
    ]
