# Generated by Django 5.2.6 on 2025-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden_id', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_produccion', 'en_produccion'), ('terminado', 'terminado'), ('en_almacen', 'en_almacen'), ('entregado', 'entregado')], default='en_produccion', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Cuadro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden_id', models.IntegerField()),
                ('varilla_id', models.IntegerField()),
                ('cant_varilla_plan', models.IntegerField(default=0)),
                ('cant_cuadros_plan', models.IntegerField(default=0)),
                ('cant_varilla_usada', models.IntegerField(default=0)),
                ('cant_cuadros_prod', models.IntegerField(default=0)),
                ('merma', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'DetalleOrden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('varilla_id', models.IntegerField()),
                ('tipo', models.CharField(choices=[('entrada', 'entrada'), ('salida', 'salida'), ('ajuste', 'ajuste'), ('transferencia', 'transferencia')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('orden_id', models.IntegerField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MovimientoInventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('solicitado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_produccion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('en_proceso', 'en_proceso'), ('completada', 'completada'), ('cancelada', 'cancelada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'OrdenProduccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Varilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Varilla',
                'managed': False,
            },
        ),
    ]
