# Generated by Django 5.2.6 on 2025-09-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('fecha_creacion', models.DateField(blank=True, default=None, null=True)),
                ('solicitado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_produccion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la orden de producción', null=True)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio de producción', null=True)),
                ('fecha_entrega', models.DateField(blank=True, help_text='Fecha de entrega estimada', null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', help_text='Prioridad de la orden', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orden_produccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('material_type', models.CharField(choices=[('varilla', 'varilla'), ('pintura_acabado', 'pintura_acabado'), ('material_impresion', 'material_impresion'), ('material_recordatorio', 'material_recordatorio'), ('software_equipo', 'software_equipo'), ('material_pintura', 'material_pintura'), ('material_diseno', 'material_diseno'), ('producto_terminado', 'producto_terminado')], max_length=25)),
                ('material_id', models.IntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia'), ('merma', 'Merma'), ('uso_produccion', 'Uso en Producción')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orden_produccion', models.ForeignKey(db_column='orden_produccion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_movimientos', to='production.ordenproduccion')),
            ],
            options={
                'db_table': 'production_movimiento_inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cant_varilla_plan', models.IntegerField(default=0)),
                ('cant_cuadros_plan', models.IntegerField(default=0)),
                ('cant_varilla_usada', models.IntegerField(default=0)),
                ('cant_cuadros_prod', models.IntegerField(default=0)),
                ('merma', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('varilla', models.ForeignKey(db_column='varilla_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.varilla')),
                ('orden', models.ForeignKey(db_column='orden_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='production.ordenproduccion')),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_produccion', 'En Producción'), ('terminado', 'Terminado'), ('en_almacen', 'En Almacén'), ('en_tienda', 'En Tienda'), ('entregado', 'Entregado'), ('vendido', 'Vendido')], default='en_produccion', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(db_column='orden_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.ordenproduccion')),
            ],
            options={
                'db_table': 'cuadro',
                'managed': True,
            },
        ),
    ]
