# Generated by Django 5.2.6 on 2025-09-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuadro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ordenproduccion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='varilla',
            options={'managed': True},
        ),
    ]
