# Generated by Django 5.2.6 on 2025-09-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialVarilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_type', models.CharField(choices=[('pintura_acabado', 'pintura_acabado'), ('material_impresion', 'material_impresion'), ('material_recordatorio', 'material_recordatorio'), ('software_equipo', 'software_equipo'), ('material_pintura', 'material_pintura'), ('material_diseno', 'material_diseno')], max_length=25)),
                ('material_id', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('varilla', models.ForeignKey(db_column='varilla_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.varilla')),
            ],
            options={
                'db_table': 'material_varilla',
                'managed': True,
            },
        ),
    ]
