# Generated by Django 5.2.6 on 2025-09-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialdiseno',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materialimpresion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materialpintura',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materialrecordatorio',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materialvarilla',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pinturaacabado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productoterminado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='softwareequipo',
            options={'managed': True},
        ),
    ]
