# Generated by Django 5.2.6 on 2025-09-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'managed': True},
        ),
    ]
