# Generated by Django 5.2.6 on 2025-09-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin_alter_users_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersverificationcode',
            name='temp_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
