# Generated by Django 5.2.6 on 2025-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_usersverificationcode_temp_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='documenttypes',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usersverificationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Código de Verificación', 'verbose_name_plural': 'Códigos de Verificación'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro del administrador'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(help_text='Dirección de correo electrónico única', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='first_name',
            field=models.CharField(blank=True, help_text='Nombre del administrador', max_length=150),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta del administrador está activa'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Indica si el administrador tiene permisos de staff'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último acceso al sistema', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_name',
            field=models.CharField(blank=True, help_text='Apellido del administrador', max_length=150),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(help_text='Contraseña hasheada del administrador', max_length=150),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(help_text='Nombre de usuario único para el administrador', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttypes',
            name='name',
            field=models.CharField(help_text='Nombre del tipo de documento (ej: DNI, Pasaporte, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_statement',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='Estado de la cuenta del usuario', max_length=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='country_id',
            field=models.IntegerField(blank=True, help_text='ID del país del usuario', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del usuario'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro del usuario'),
        ),
        migrations.AlterField(
            model_name='users',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación lógica (soft delete)', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='document_number',
            field=models.CharField(help_text='Número de documento de identidad único', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='document_type_id',
            field=models.IntegerField(blank=True, help_text='ID del tipo de documento del usuario', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(help_text='Dirección de correo electrónico única', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de verificación del email', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta está activa'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si tiene permisos de staff'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Indica si es superusuario del sistema'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último login', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_session',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última sesión activa'),
        ),
        migrations.AlterField(
            model_name='users',
            name='maternal_lastname',
            field=models.CharField(help_text='Apellido materno del usuario', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(help_text='Nombre del usuario', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='password_change',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña'),
        ),
        migrations.AlterField(
            model_name='users',
            name='paternal_lastname',
            field=models.CharField(help_text='Apellido paterno del usuario', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo_url',
            field=models.CharField(blank=True, help_text='URL de la foto de perfil del usuario', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='remember_token',
            field=models.CharField(blank=True, help_text='Token para recordar sesión del usuario', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Sexo del usuario', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='tenant_id',
            field=models.IntegerField(help_text='ID del tenant para soporte multi-tenancy'),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(help_text='Nombre de usuario único para login', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usersverificationcode',
            name='code',
            field=models.CharField(blank=True, help_text='Código de verificación generado', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del código'),
        ),
        migrations.AlterField(
            model_name='usersverificationcode',
            name='expires_at',
            field=models.DateTimeField(help_text='Fecha y hora de expiración del código'),
        ),
        migrations.AlterField(
            model_name='usersverificationcode',
            name='failed_attempts',
            field=models.IntegerField(default=0, help_text='Número de intentos fallidos de verificación'),
        ),
        migrations.AlterField(
            model_name='usersverificationcode',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la cual el código está bloqueado por intentos fallidos', null=True),
        ),
        migrations.AlterField(
            model_name='usersverificationcode',
            name='temp_email',
            field=models.CharField(blank=True, help_text='Email temporal almacenado para cambios de email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersverificationcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización'),
        ),
        migrations.AlterField(
            model_name='usersverificationcode',
            name='user_id',
            field=models.BigIntegerField(blank=True, help_text='ID del usuario propietario del código de verificación', null=True),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['document_number'], name='users_documen_f7a4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['tenant_id'], name='users_tenant__d262cd_idx'),
        ),
        migrations.AddIndex(
            model_name='usersverificationcode',
            index=models.Index(fields=['user_id'], name='users_verif_user_id_ecd76a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersverificationcode',
            index=models.Index(fields=['expires_at'], name='users_verif_expires_885c67_idx'),
        ),
        migrations.AddIndex(
            model_name='usersverificationcode',
            index=models.Index(fields=['code'], name='users_verif_code_979060_idx'),
        ),
    ]
