# Generated by Django 5.2.6 on 2025-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('item_type', models.CharField(choices=[('varilla', 'varilla'), ('pintura_acabado', 'pintura_acabado'), ('material_impresion', 'material_impresion'), ('material_recordatorio', 'material_recordatorio'), ('software_equipo', 'software_equipo'), ('material_pintura', 'material_pintura'), ('material_diseno', 'material_diseno'), ('producto_terminado', 'producto_terminado')], max_length=25)),
                ('item_id', models.IntegerField()),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Inventario',
                'managed': False,
            },
        ),
    ]
