# Generated by Django 5.2.6 on 2025-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Inventario')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre del Producto')),
                ('categoria', models.CharField(choices=[('Molduras', 'Molduras'), ('Impresión Fotográfica', 'Impresión Fotográfica'), ('Pinturas y Acabados', 'Pinturas y Acabados'), ('Papel', 'Papel'), ('Químicos', 'Químicos'), ('Insumos', 'Insumos'), ('Herramientas', 'Herramientas'), ('Materiales', 'Materiales'), ('Pinturas', 'Pinturas'), ('Pinceles', 'Pinceles'), ('Software', 'Software'), ('Hardware', 'Hardware')], default='Molduras', max_length=50, verbose_name='Categoría')),
                ('tipo', models.CharField(choices=[('Moldura', 'Moldura'), ('Papel', 'Papel'), ('Consumible', 'Consumible'), ('Pintura', 'Pintura'), ('Barniz', 'Barniz'), ('Químico', 'Químico'), ('Herramienta', 'Herramienta'), ('Material', 'Material'), ('Pincel', 'Pincel'), ('Software', 'Software'), ('Hardware', 'Hardware')], default='Moldura', max_length=50, verbose_name='Tipo')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('stockMinimo', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('unidad', models.CharField(choices=[('unidades', 'Unidades'), ('Hojas', 'Hojas'), ('L', 'Litros'), ('rollos', 'Rollos'), ('kg', 'Kilogramos')], default='unidades', max_length=20, verbose_name='Unidad')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor')),
                ('fechaIngreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('ultimaVenta', models.DateField(blank=True, null=True, verbose_name='Última Venta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['-fechaIngreso'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDiseno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_material_diseno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialImpresion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_material_impresion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialPintura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_material_pintura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialRecordatorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_material_recordatorio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia'), ('merma', 'Merma')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PinturaAcabado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_pintura_acabado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('en_produccion', 'En Producción'), ('en_almacen', 'En Almacén'), ('en_tienda', 'En Tienda'), ('vendido', 'Vendido')], default='en_produccion', max_length=20)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_producto_terminado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SoftwareEquipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_software_equipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Varilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'varilla',
                'managed': True,
            },
        ),
    ]
