# Generated by Django 5.2.6 on 2025-09-13 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='orden',
            field=models.ForeignKey(blank=True, db_column='orden_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movimientos', to='production.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, db_column='orden_produccion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='varilla',
            field=models.ForeignKey(db_column='varilla_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.varilla'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('id', 'tenant')},
        ),
    ]
