# Generated by Django 5.2.6 on 2025-09-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(choices=[('Enmarcado', 'Enmarcado'), ('Minilab', 'Minilab'), ('Pintura', 'Pintura'), ('Diseño', 'Diseño'), ('Restauración Digital', 'Restauración Digital'), ('Recordatorios', 'Recordatorios')], default='Enmarcado', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo',
            field=models.CharField(choices=[('Molduras', 'Molduras'), ('Pinturas', 'Pinturas'), ('Pinceles', 'Pinceles'), ('Barnices', 'Barnices'), ('Papel', 'Papel'), ('Químicos', 'Químicos'), ('Insumos', 'Insumos'), ('Óleos', 'Óleos'), ('Acrílicos', 'Acrílicos'), ('Lienzos', 'Lienzos'), ('Plantillas', 'Plantillas'), ('Fuentes', 'Fuentes'), ('Gráficos', 'Gráficos'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Materiales', 'Materiales'), ('Herramientas', 'Herramientas')], default='Molduras', max_length=50, verbose_name='Tipo'),
        ),
    ]
