# Generated by Django 5.2.6 on 2025-09-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventario',
            table='inventario',
        ),
    ]
