# Generated by Django 5.2.6 on 2025-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('contacto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto')),
                ('tipo', models.CharField(choices=[('individual', 'Particular'), ('school', 'Colegio'), ('business', 'Empresa')], default='individual', max_length=20, verbose_name='Tipo de Cliente')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('ie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución Educativa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultimo_pedido', models.DateField(blank=True, null=True, verbose_name='Último Pedido')),
                ('total_pedidos', models.IntegerField(default=0, verbose_name='Total de Pedidos')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'client',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
