# Generated by Django 5.2.6 on 2025-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('confirmada', 'confirmada'), ('completada', 'completada'), ('cancelada', 'cancelada')], default='pendiente', max_length=20)),
                ('client', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duración')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('type', models.CharField(choices=[('reunion', 'Reunión'), ('sesion', 'Sesión'), ('entrega', 'Entrega')], default='sesion', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('participants', models.PositiveIntegerField(default=0, verbose_name='Participantes')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('tasks', models.JSONField(blank=True, default=list, verbose_name='Tareas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agenda',
                'managed': True,
            },
        ),
    ]
