# Generated by Django 5.2.6 on 2025-09-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'managed': True},
        ),
    ]
