# Generated by Django 5.2.6 on 2025-09-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agenda_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agenda',
            table='agenda',
        ),
    ]
